/** Titles generated by the schedule-run UI follow `M/D HH:mm - TaskName`. */
export function isScheduleRunConversationTitle(title: string | undefined): title is string {
  return /^\d{1,2}\/\d{1,2} \d{2}:\d{2} - .+/.test(title?.trim() ?? '');
}
